export const lines = [
  { user: true, line: 'whoami' },
  { line: 'Adam Zielonka' },
  { line: '' },
  { line: '[EMAIL]' },
  { line: '[root@adamzielonka.pro](mailto:root@adamzielonka.pro)' },
  { line: '' },
  { line: '[REPO]' },
  { line: '[bitbucket.org/adam-zielonka-pro/](https://bitbucket.org/adam-zielonka-pro/)' },
  { line: '' },
  { line: '[APPS]' },
  { line: 'Server Status: [Source](https://bitbucket.org/adam-zielonka-pro/server-status/src), [Demo](https://fake-status.adamzielonka.pro/)' },
  { line: 'Unit Converter: [Google Play](https://play.google.com/store/apps/details?id=pro.adamzielonka.converter)' },
  { line: 'paintAZ: [Source](https://bitbucket.org/adam-zielonka-pro/programowanie-wieloplatformowe-paint-qt/src)' },
  { line: '' },
  { line: '[GAMES]' },
  { line: 'Ships: [Source](https://bitbucket.org/adam-zielonka-pro/jezyki-interpretowane/src), [Play](https://adamzielonka.pro/statki.html)' },
  { line: 'GameOfLife: [Source](https://bitbucket.org/adam-zielonka-pro/jezyki-interpretowane/src/75a6444ff620f4c213af981301b585d872d70008/gameOfLife.html), [Play](https://adamzielonka.pro/gameOfLife.html)' },
  { line: 'Pan: [Source](https://bitbucket.org/adam-zielonka-pro/pan/src), [Play](https://angular.adamzielonka.pro/)' },
  { line: 'Chińczyk: [Source](https://bitbucket.org/adam-zielonka-pro/chinczyk/src), [Play](https://react.adamzielonka.pro/)' },
  { line: '' },
  { user: true, line: 'description' },
  { line: '[PL] Człowiek programista. Informatyk' },
  { line: '[EN] Programmerman. Computer scientist' },
  { line: '' },
  { user: true, line: '' },
]
